### ISSUE TITLE
Need BLE examples

### ISSUE THREAD

**Issue by mlemainque** [JimmySoftware/ESPert#4]
Hi,

I saw that you had written a BLE class, but without any usage example
Does it mean that the new Espresso Lite can act as a BLE device, without any extra hardware?
That would be awesome !!

Thanks,
Matthias

**Comment by mozeal** [comment]
Yes and No.

The future board will have 2 version. One based on ESP8266 which will have BLE unit connected via UART (we plan to use HM-12 BLE unit for this).

Another board, which based on ESP-32 will have BLE support in chip. (Expected to released Q2-2016)

Thanks.
Jimmy
